### ISSUE TITLE
working inline image doesn't export

### ISSUE THREAD

**Issue by paynito** [redguardtoo/org-mime#4]
Do images export to html mime mail messages?

error on C-c C-s:
Opening input file: no such file or directory: /var/folders ... /

`
# +STARTUP: inlineimages

**\* a picture
[[file:/Users/me/Pictures/els.jpg]]
<#/multipart>
<#part type="image/jpg" filename="/var/folders/wb/cfz8yrnd3gs8570lx2l291sh0000gn/T/file:/Users/me/els.jpg" disposition=inline id="<_var_folders_wb_cfz8yrnd3gs8570lx2l291sh0000gn_T_file:_Users_me_Pictures_els.jpg>">
<#/part>
`

**Comment by redguardtoo** [comment]
I will look into this. Can you show me a step and step report?

**Comment by paynito** [comment]
I start in [mimeOnlyimg.org](https://gist.githubusercontent.com/paynito/7b2c05446f447103ed39f03dbefe2b3a/raw/361bb89d837a9170ca9d3e842f56470651f24dc8/mimeOnlyimg.org)

I call the function `'org-mime-org-buffer-htmlize`

This gives me this [mail buffer](https://gist.github.com/paynito/171e1c1418a8f6f54b09e4744f95ceff)

mu4e.   Sending C-c C-s. gives [an error](https://gist.github.com/25b2e4d555a37918e5141ed76d9476d0)

I am able to htmlize and send .org files with headings and src code blocks, just not images.

**Comment by redguardtoo** [comment]
b33c96b embedded image could use absolute path (Chen Bin)

**Comment by benyomin** [comment]
could use / should use /must use ??
会用
可以用
应该使用
isn't there some elisp that can resolve a relative path like ~/ to /Users/me ?

**Comment by redguardtoo** [comment]
It's not like you thought. anyway, it's already fixed.

**Comment by paynito** [comment]
here's what I get after upgrading to spacemacs .2 
`Using account nil
Mark set [2 times]
org-export-as: Wrong number of arguments: #[(templates) "ebÆÇÈÆÉ#\\Ê Ë  !Ì=XÍ  
\"ÎÏ \"   ÎÐ    \"E<ÑÒÎÓ   \"\"WW
BÎÔ    \"bÕÆx`|c)+)*" [record object templates value begin signature nil re-search-forward "{{{[-A-Za-z0-9_]" t ...] 6 ("/usr/local/Cellar/emacs-plus/HEAD-5ee56c4/share/emacs/25.2.50/lisp/org/org-macro.elc" . 3784)], 3`

**Comment by redguardtoo** [comment]
Could you `M-x toggle-debug-on-error` and show me the full error message? Maybe Emacs v25 changed some internal API.

I tested with Emacs 25.1, it's working in both org-mode and message-mode. Please note I only support Emacs stable version 23.4, 24.3, 24.4, 25.1

**Comment by paynito** [comment]
working now, closing.
